name: find_me_a_coach
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  shared_preferences:
  flutter_screenutil: ^5.9.0
  flutter_svg:
  flutter_spinkit:
  image_picker: ^1.1.2
  image_cropper:
  intl: ^0.20.2
  cached_network_image:
  shimmer:
  timeago:
  flutter_otp_text_field:


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/icons/
     - assets/language/
     - assets/images/





  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/font/Montserrat-Bold.ttf
         - asset: assets/font/Montserrat-ExtraBold.ttf
         - asset: assets/font/Montserrat-Light.ttf
         - asset: assets/font/Montserrat-Medium.ttf
         - asset: assets/font/Montserrat-Regular.ttf
         - asset: assets/font/Montserrat-SemiBold.ttf



